COLUMNS:   
  gender: object 
  age: int64
  city: object 
  membership_type: object 
  total_spend: float64
  items_purchased: int64  
  average_rating: float64
  discount_applied: bool   
  days_since_last_purchase: int64  
  satisfaction_level: object  

numerical_columns:
  age: int64
  total_spend: float64
  items_purchased: int64
  average_rating: float64
  days_since_last_purchase: int64

categorical_columns:
  gender: object
  city: object
  membership_type: object
  satisfaction_level: object

id_column:
  customer_id: int64 




    


